server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  cache:
    type: simple
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: 'jdbc:mysql://localhost:3306/scoredb'
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true